export const SET_ENVIRONMENT = 'SET_ENVIRONMENT';

export const RESET_STATE = 'RESET_STATE';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_START = 'RESET_START';
export const RESET_COMPLETED = 'RESET_COMPLETED';
export const RESET_POPUP = 'RESET_POPUP';
export const CHANGE_STATE = 'CHANGE_STATE';
export const CHANGE_MAIN_TAB = 'CHANGE_MAIN_TAB';
export const DISABLE_SUMMARY_TAB = 'DISABLE_SUMMARY_TAB';
export const DISABLE_TRAIN_TAB = 'DISABLE_TRAIN_TAB';
export const DISABLE_LEADERBOARD_TAB = 'DISABLE_LEADERBOARD_TAB';
export const DISABLE_PREDICT_TAB = 'DISABLE_PREDICT_TAB';
export const IMPORT_DATA_FILE_START = 'IMPORT_DATA_FILE_START';
export const IMPORT_DATA_FILE_COMPLETED = 'IMPORT_DATA_FILE_COMPLETED';
export const IMPORT_UPLOAD_FILENAME = 'IMPORT_UPLOAD_FILENAME';
export const IMPORT_FILENAME = 'IMPORT_FILENAME';
export const IMPORT_FILE_DONE = 'IMPORT_FILE_DONE';
export const PARSE_SETUP_START = 'PARSE_SETUP_START';
export const PARSE_SETUP_COMPLETED = 'PARSE_SETUP_COMPLETED';
export const PARSE_START = 'PARSE_START';
export const PARSE_IN_PROGRESS = 'PARSE_IN_PROGRESS';
export const PARSE_COMPLETED = 'PARSE_COMPLETED';
export const CHANGE_COLUMN_TYPE = 'CHANGE_COLUMN_TYPE';
export const CHANGE_COLUMN_FLAG = 'CHANGE_COLUMN_FLAG';
export const SUMMARY_SELECT_ALL_COLUMNS = 'SUMMARY_SELECT_ALL_COLUMNS';
export const CHANGE_TARGET_COLUMN = 'CHANGE_TARGET_COLUMN';
export const OPEN_SETTINGS_TRAIN = 'OPEN_SETTINGS_TRAIN';

export const TRAIN_SELECT_MODEL = 'TRAIN_SELECT_MODEL';
export const TRAIN_SELECT_ALL_MODELS = 'TRAIN_SELECT_ALL_MODELS';
export const TRAIN_APPLY_SETTINGS = 'TRAIN_APPLY_SETTINGS';

export const TRAIN_START = 'TRAIN_START';
export const TRAIN_IN_PROGRESS = 'TRAIN_IN_PROGRESS';
export const TRAIN_COMPLETED = 'TRAIN_COMPLETED';
export const TRAIN_ERROR = 'TRAIN_ERROR';


export const LEADERBOARD_DATA = 'LEADERBOARD_DATA';
export const LEADERBOARD_SORT = 'LEADERBOARD_SORT';

export const PREDICT_MODEL_SELECT = 'PREDICT_MODEL_SELECT';
export const PREDICT_MODEL_METRICS = 'PREDICT_MODEL_METRICS';

export const PREDICT_START = 'PREDICT_START';
export const PREDICT_COMPLETED = 'PREDICT_COMPLETED';
export const PREDICT_FRAME_NAME = 'PREDICT_FRAME_NAME';
export const PREDICT_RESULT = 'PREDICT_RESULT';
export const PREDICT_ERROR = 'PREDICT_ERROR';
